import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import type { AttributeDefinition, Category, CategoryListHeader } from "@shared/types";
import { Loading } from "../components/ui/Loading";
import { apiClient } from "../lib/api-client";

const FIELD_OPTIONS: { value: string; label: string }[] = [
  { value: "modelNumber", label: "型番・部品名" },
  { value: "description", label: "説明" },
  { value: "manufacturer", label: "メーカー" },
  { value: "categoryName", label: "カテゴリ" },
  { value: "status", label: "ステータス" },
  { value: "location", label: "保管場所" },
  { value: "stockQuantity", label: "在庫数" },
  { value: "actions", label: "操作" },
];

const FIELD_LABELS: Record<string, string> = Object.fromEntries(FIELD_OPTIONS.map((f) => [f.value, f.label]));
const HIDDEN_FIELD_KEYS = new Set(["archived"]);

type UnifiedRow = {
  rowType: "builtin" | "spec";
  fieldKey?: string | null;
  label: string;
  dataType: "text" | "number" | "boolean" | "date";
  unit: string;
  isSearchable: boolean;
  sortOrder: number;
  isVisible: boolean;
  attributeId?: number;
  headerId?: number;
  /** Tracks the original attribute key for remapping after save */
  _originalKey?: string;
};

function mergeToRows(attrs: AttributeDefinition[], headers: CategoryListHeader[]): UnifiedRow[] {
  const rows: UnifiedRow[] = [];
  const usedAttrIds = new Set<number>();

  for (const h of headers) {
    if (h.fieldKey && HIDDEN_FIELD_KEYS.has(h.fieldKey)) continue;

    if (h.fieldKey) {
      rows.push({
        rowType: "builtin",
        fieldKey: h.fieldKey,
        label: h.label,
        dataType: "text",
        unit: "",
        isSearchable: false,
        sortOrder: h.sortOrder,
        isVisible: h.isVisible,
        headerId: h.id,
      });
    } else if (h.attributeDefinitionId && h.attributeDefinition) {
      const ad = h.attributeDefinition;
      usedAttrIds.add(ad.id);
      rows.push({
        rowType: "spec",
        label: h.label,
        dataType: ad.dataType,
        unit: ad.unit ?? "",
        isSearchable: ad.isSearchable,
        sortOrder: h.sortOrder,
        isVisible: h.isVisible,
        attributeId: ad.id,
        headerId: h.id,
        _originalKey: ad.key,
      });
    }
  }

  // Attributes not referenced by any header
  for (const ad of attrs) {
    if (!usedAttrIds.has(ad.id)) {
      rows.push({
        rowType: "spec",
        label: ad.label,
        dataType: ad.dataType,
        unit: ad.unit ?? "",
        isSearchable: ad.isSearchable,
        sortOrder: ad.sortOrder,
        isVisible: false,
        attributeId: ad.id,
        _originalKey: ad.key,
      });
    }
  }

  rows.sort((a, b) => a.sortOrder - b.sortOrder);
  return rows;
}

export function CategorySettingsPage() {
  const { id: categoryIdStr } = useParams();
  const categoryId = Number(categoryIdStr);

  const [category, setCategory] = useState<Category | null>(null);
  const [rows, setRows] = useState<UnifiedRow[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    Promise.all([
      apiClient.listCategories().then((cats) => cats.find((c) => c.id === categoryId) || null),
      apiClient.listCategoryAttributes(categoryId),
      apiClient.listCategoryHeaders(categoryId),
    ])
      .then(([cat, attrData, headerData]) => {
        setCategory(cat);
        setRows(mergeToRows(attrData, headerData));
      })
      .catch((err) => setError(err.message))
      .finally(() => setIsLoading(false));
  }, [categoryId]);

  async function handleSave() {
    // Validate
    for (const row of rows) {
      if (!row.label.trim()) {
        setError("表示名は必須です。");
        return;
      }
      if (row.rowType === "builtin" && !row.fieldKey) {
        setError("基本列のフィールドを選択してください。");
        return;
      }
    }

    setIsSaving(true);
    setMessage("");
    setError("");
    try {
      // 1. Build attributes from spec rows (key is auto-generated by backend)
      const specRows = rows.filter((r) => r.rowType === "spec");
      const attrInputs = specRows.map((r, i) => ({
        id: r.attributeId,
        label: r.label,
        dataType: r.dataType,
        unit: r.unit || null,
        isSearchable: r.isSearchable,
        sortOrder: i * 10,
      }));

      await apiClient.updateCategoryAttributes(categoryId, attrInputs);
      const savedAttrs = await apiClient.listCategoryAttributes(categoryId);

      // 2. Build headers from all rows, remapping attributeDefinitionIds
      const headerInputs = rows.map((r, i) => {
        if (r.rowType === "builtin") {
          return {
            id: r.headerId,
            fieldKey: r.fieldKey as CategoryListHeader["fieldKey"],
            attributeDefinitionId: null,
            label: r.label,
            sortOrder: i * 10,
            isVisible: r.isVisible,
          };
        }
        // Spec row: find the saved attribute by matching
        let attrId: number | null = null;
        if (r.attributeId && savedAttrs.some((a) => a.id === r.attributeId)) {
          attrId = r.attributeId;
        } else {
          // Match by label (for newly created attrs)
          const match = savedAttrs.find((a) => a.label === r.label);
          attrId = match?.id ?? null;
        }
        return {
          id: r.headerId,
          fieldKey: null,
          attributeDefinitionId: attrId,
          label: r.label,
          sortOrder: i * 10,
          isVisible: r.isVisible,
        };
      });

      await apiClient.updateCategoryHeaders(categoryId, headerInputs);
      const savedHeaders = await apiClient.listCategoryHeaders(categoryId);

      // Reload unified state
      setRows(mergeToRows(savedAttrs, savedHeaders));
      setMessage("設定を保存しました。");
    } catch (err) {
      setError(err instanceof Error ? err.message : "保存に失敗しました。");
    } finally {
      setIsSaving(false);
    }
  }

  function updateRow(index: number, patch: Partial<UnifiedRow>) {
    setRows((prev) => prev.map((r, i) => (i === index ? { ...r, ...patch } : r)));
  }

  function removeRow(index: number) {
    setRows((prev) => prev.filter((_, i) => i !== index));
  }

  function addBuiltin() {
    setRows((prev) => [
      ...prev,
      {
        rowType: "builtin",
        fieldKey: "",
        label: "",
        dataType: "text",
        unit: "",
        isSearchable: false,
        sortOrder: prev.length * 10,
        isVisible: true,
      },
    ]);
  }

  function addSpec() {
    setRows((prev) => [
      ...prev,
      {
        rowType: "spec",
        label: "",
        dataType: "text",
        unit: "",
        isSearchable: true,
        sortOrder: prev.length * 10,
        isVisible: true,
      },
    ]);
  }

  if (isLoading) return <Loading />;
  if (!category) return <div className="p-4 text-app-danger">カテゴリが見つかりません。</div>;

  return (
    <div className="mx-auto max-w-5xl space-y-6 pb-20">
      <header className="flex items-center justify-between border-b border-slate-200 pb-4">
        <div>
          <nav className="mb-1 flex items-center gap-2 text-xs text-slate-500">
            <Link to="/categories" className="hover:text-app-link hover:underline">カテゴリ管理</Link>
            <span>/</span>
            <span className="font-semibold text-slate-900">{category.name}</span>
          </nav>
          <h1 className="text-xl font-bold text-slate-900">カテゴリ設定</h1>
          <p className="mt-1 text-xs text-slate-500">仕様項目の定義と、部品一覧での表示列を設定します。</p>
        </div>
        <div className="flex items-center gap-3">
          {message && <span className="text-sm font-medium text-app-link">{message}</span>}
          {error && <span className="text-sm font-medium text-app-danger">{error}</span>}
          <button className="btn btn-primary h-10 px-6" onClick={handleSave} disabled={isSaving}>
            {isSaving ? "保存中..." : "変更を保存"}
          </button>
        </div>
      </header>

      <section className="panel-card">
        <div className="border-b border-slate-100 p-4">
          <h2 className="text-base font-bold text-slate-900">表示列・仕様項目</h2>
          <p className="mt-1 text-xs text-slate-500">部品一覧に表示する列と、部品が持つ仕様項目を一元管理します。</p>
        </div>
        <div className="space-y-3 p-4">
          {rows.map((row, index) => (
            <div key={index} className="rounded-lg border border-slate-200 bg-slate-50 p-3">
              {row.rowType === "builtin" ? (
                <BuiltinRowEditor row={row} index={index} onUpdate={updateRow} onRemove={removeRow} />
              ) : (
                <SpecRowEditor row={row} index={index} onUpdate={updateRow} onRemove={removeRow} />
              )}
            </div>
          ))}

          {rows.length === 0 && (
            <p className="py-6 text-center text-sm text-slate-400">まだ項目がありません。下のボタンから追加してください。</p>
          )}

          <div className="flex gap-2">
            <button
              className="flex-1 rounded-lg border-2 border-dashed border-slate-200 py-3 text-sm font-medium text-slate-500 hover:border-app-link hover:text-app-link transition-colors"
              onClick={addBuiltin}
            >
              ＋ 基本列を追加
            </button>
            <button
              className="flex-1 rounded-lg border-2 border-dashed border-slate-200 py-3 text-sm font-medium text-slate-500 hover:border-app-link hover:text-app-link transition-colors"
              onClick={addSpec}
            >
              ＋ 仕様項目を追加
            </button>
          </div>
        </div>
      </section>
    </div>
  );
}

function BuiltinRowEditor({
  row,
  index,
  onUpdate,
  onRemove,
}: {
  row: UnifiedRow;
  index: number;
  onUpdate: (i: number, patch: Partial<UnifiedRow>) => void;
  onRemove: (i: number) => void;
}) {
  return (
    <div className="grid gap-2">
      <div className="flex items-center gap-2">
        <span className="rounded bg-slate-200 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-slate-500">基本列</span>
      </div>
      <div className="grid grid-cols-2 gap-2">
        <div className="space-y-1">
          <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">フィールド</label>
          <select
            className="w-full rounded border border-slate-300 px-2 py-1.5 text-sm"
            value={row.fieldKey || ""}
            onChange={(e) => {
              const key = e.target.value;
              const patch: Partial<UnifiedRow> = { fieldKey: key || null };
              if (key && !row.label.trim() && FIELD_LABELS[key]) {
                patch.label = FIELD_LABELS[key];
              }
              onUpdate(index, patch);
            }}
          >
            <option value="">選択してください</option>
            {FIELD_OPTIONS.map((f) => (
              <option key={f.value} value={f.value}>{f.label}</option>
            ))}
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">表示名</label>
          <input
            className="w-full rounded border border-slate-300 px-2 py-1.5 text-sm"
            value={row.label}
            onChange={(e) => onUpdate(index, { label: e.target.value })}
            placeholder="例: 型番"
          />
        </div>
      </div>
      <RowFooter row={row} index={index} onUpdate={onUpdate} onRemove={onRemove} />
    </div>
  );
}

function SpecRowEditor({
  row,
  index,
  onUpdate,
  onRemove,
}: {
  row: UnifiedRow;
  index: number;
  onUpdate: (i: number, patch: Partial<UnifiedRow>) => void;
  onRemove: (i: number) => void;
}) {
  return (
    <div className="grid gap-2">
      <div className="flex items-center gap-2">
        <span className="rounded bg-blue-100 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-blue-600">仕様項目</span>
      </div>
      <div className="grid grid-cols-2 gap-2">
        <div className="space-y-1">
          <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">項目名</label>
          <input
            className="w-full rounded border border-slate-300 px-2 py-1.5 text-sm"
            value={row.label}
            onChange={(e) => onUpdate(index, { label: e.target.value })}
            placeholder="例: 抵抗値"
          />
        </div>
        <div className="grid grid-cols-2 gap-2">
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">データ型</label>
            <select
              className="w-full rounded border border-slate-300 px-2 py-1.5 text-sm"
              value={row.dataType}
              onChange={(e) => onUpdate(index, { dataType: e.target.value as UnifiedRow["dataType"] })}
            >
              <option value="text">テキスト</option>
              <option value="number">数値</option>
              <option value="boolean">真偽値</option>
              <option value="date">日付</option>
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">単位</label>
            <input
              className="w-full rounded border border-slate-300 px-2 py-1.5 text-sm"
              value={row.unit}
              onChange={(e) => onUpdate(index, { unit: e.target.value })}
              placeholder="例: Ω"
            />
          </div>
        </div>
      </div>
      <RowFooter row={row} index={index} onUpdate={onUpdate} onRemove={onRemove} showSearchable />
    </div>
  );
}

function RowFooter({
  row,
  index,
  onUpdate,
  onRemove,
  showSearchable,
}: {
  row: UnifiedRow;
  index: number;
  onUpdate: (i: number, patch: Partial<UnifiedRow>) => void;
  onRemove: (i: number) => void;
  showSearchable?: boolean;
}) {
  return (
    <div className="flex items-center justify-between border-t border-slate-200 pt-2">
      <div className="flex items-center gap-4">
        <label className="flex items-center gap-2 text-xs font-medium text-slate-600">
          <input
            type="checkbox"
            checked={row.isVisible}
            onChange={(e) => onUpdate(index, { isVisible: e.target.checked })}
          />
          一覧に表示
        </label>
        {showSearchable && (
          <label className="flex items-center gap-2 text-xs font-medium text-slate-600">
            <input
              type="checkbox"
              checked={row.isSearchable}
              onChange={(e) => onUpdate(index, { isSearchable: e.target.checked })}
            />
            検索対象
          </label>
        )}
      </div>
      <button className="text-xs font-medium text-app-danger hover:underline" onClick={() => onRemove(index)}>削除</button>
    </div>
  );
}
